"""A stand-in for `claude -p` that answers from the prompt alone.

Selected with ``ROBUSTO_BACKEND=mock`` or ``--backend mock``. It makes no model
call and spends no tokens. Everything else in the pipeline runs for real: the
deterministic parse, prompt rendering, the schema contract, JSON recovery,
validation, the bounded retry, normalisation, editor-input assembly, and the
final-report check. That is the whole point: those stages can be exercised end
to end, on a real manuscript, before a single reviewer token is spent, and in CI
where no CLI is logged in.

The mock decides what it is being asked from the prompt text on stdin, the same
way the model would:

    probe      the environment check's nonce, echoed back
    reviewer   ``- reviewer = "..."`` plus an inlined output contract
    selector   ``Act as the reviewer_applicability_router``
    editor     ``Act as the editor for this run``

A reviewer reply is a synthetic but fully valid JSON object: real finding ids in
the reviewer's prefix, a source object pointing at a file that exists under the
run's ``parsed/`` directory, a ``cannot_verify`` finding to exercise that route,
copyedit findings from the grammar auditor so the editor must produce the
grammar appendix, and a medium-severity parser finding from the preflight
auditor so the warning path fires without blocking.

Two knobs exist to exercise the paths that only misbehaviour reaches:

    ROBUSTO_MOCK_DRIFT=name[,name]   first reply breaks the contract, the retry
                                     succeeds
    ROBUSTO_MOCK_FAIL=name[,name]    every reply breaks the contract, so the
                                     reviewer fails loudly after one retry

And two to shape the run:

    ROBUSTO_MOCK_FINDINGS=N          findings per reviewer (default 2)
    ROBUSTO_MOCK_SKIP=name[,name]    optional reviewers the selector skips

Every synthetic artifact says so on its face. The report opens with a banner,
each finding summary names the mock, and the run manifest records the backend,
so nothing produced here can pass for a review.
"""

from __future__ import annotations

import hashlib
import json
import os
import re
import sys
from pathlib import Path

PROBE_TOKEN = "robusto-probe-ok"
RETRY_MARKER = "did not satisfy the output contract"
CONTRACT_MARKER = "# Output contract"
EDITOR_MARKER = "Act as the editor for this run"
SELECTOR_MARKER = "Act as the reviewer_applicability_router"

MOCK_NOTE = "Generated by the robusto mock backend; synthetic, not a review."


def env_names(name: str) -> set[str]:
    return {item.strip() for item in os.environ.get(name, "").split(",") if item.strip()}


def env_int(name: str, default: int) -> int:
    try:
        return int(os.environ.get(name, "") or default)
    except ValueError:
        return default


def first(pattern: str, text: str) -> str | None:
    match = re.search(pattern, text)
    return match.group(1) if match else None


def json_blocks(text: str) -> list[object]:
    """Every fenced JSON block that parses, in order."""
    found = []
    for match in re.finditer(r"```json\s*(.*?)\s*```", text, re.S):
        try:
            found.append(json.loads(match.group(1)))
        except ValueError:
            continue
    return found


def fenced_by_name(name: str) -> bool:
    """Deterministically vary reply shape so both recovery paths get exercised."""
    return int(hashlib.sha1(name.encode()).hexdigest(), 16) % 2 == 0


def emit(payload: dict, *, fenced: bool, broken: bool) -> None:
    body = json.dumps(payload, indent=2, ensure_ascii=False)
    if broken:
        # Prose either side, a fence, and a required field missing: enough to
        # fail the schema, so the retry path has something to correct.
        sys.stdout.write("Here is my assessment of the manuscript.\n\n")
        sys.stdout.write("```json\n" + body + "\n```\n\nLet me know if you need more.\n")
        return
    if fenced:
        sys.stdout.write("```json\n" + body + "\n```\n")
    else:
        sys.stdout.write(body + "\n")


# --------------------------------------------------------------------------- #
# reviewer
# --------------------------------------------------------------------------- #

def evidence_file(paper_id: str) -> str | None:
    """A repo-relative path to a real parsed artifact, forward slashes."""
    parsed = Path("work") / paper_id / "parsed"
    preferred = parsed / "full_text.md"
    if preferred.is_file():
        return preferred.as_posix()
    for candidate in sorted(parsed.glob("*")):
        if candidate.is_file():
            return candidate.as_posix()
    return None


def issue_type_for(reviewer: str) -> str:
    if reviewer == "grammar_auditor":
        return "copyedit_issue"
    if reviewer == "parser_quality_auditor":
        # medium severity: prints a warning, does not trip the preflight gate
        return "parser_artifact"
    return "manuscript_issue"


def verifiable_finding(prefix: str, index: int, reviewer: str, path: str | None) -> dict:
    fid = f"{prefix}-{index:03d}"
    source_id = f"{fid}-src-1"
    numeric_check = None
    if reviewer == "numerical_auditor":
        numeric_check = {
            "reported_value": "0.90",
            "expected_value": "0.90",
            "method": "mock recomputation",
            "inputs": ["synthetic"],
            "recomputation_notes": MOCK_NOTE,
        }
    sources = []
    links = []
    if path is not None:
        sources.append(
            {
                "id": source_id,
                "type": "parsed_artifact",
                "label": Path(path).name,
                "path": path,
                "page": None,
                "page_label": None,
                "section": None,
                "text_quote": f"synthetic quotation {index} for {reviewer}",
                "url": None,
            }
        )
        links.append(
            {
                "claim_text": f"Synthetic claim {index} from {reviewer}.",
                "source_object_ids": [source_id],
                "relation": "partial",
                "note": MOCK_NOTE,
            }
        )
    return {
        "id": fid,
        "category": "mock",
        "finding_summary": f"Mock finding {index} from {reviewer}. Synthetic, for pipeline exercise only.",
        "issue_type": issue_type_for(reviewer),
        "severity": "medium" if index == 1 else "low",
        "confidence": "medium",
        "location": {
            "page": None,
            "page_label": None,
            "section": f"Mock section {index}",
            "text_quote": f"synthetic quotation {index} for {reviewer}",
            "precision": "partial",
        },
        "claim_text": f"Synthetic claim {index} from {reviewer}.",
        "assessment": "partially",
        "cannot_verify_reason": None,
        "evidence_summary": "No evidence was examined. The mock backend fabricates a well-formed finding so downstream stages have input.",
        "source_objects": sources,
        "claim_evidence_links": links,
        "numeric_check": numeric_check,
        "suggested_fix": "None. This finding exists only to exercise the pipeline.",
    }


def cannot_verify_finding(prefix: str, index: int, reviewer: str) -> dict:
    fid = f"{prefix}-{index:03d}"
    return {
        "id": fid,
        "category": "mock",
        "finding_summary": f"Mock cannot-verify finding {index} from {reviewer}. Synthetic.",
        "issue_type": "cannot_verify",
        "severity": "low",
        "confidence": "low",
        "location": {
            "page": None,
            "page_label": None,
            "section": None,
            "text_quote": None,
            "precision": "missing",
        },
        "claim_text": f"Synthetic claim {index} from {reviewer} that the mock declines to verify.",
        "assessment": "cannot_verify",
        "cannot_verify_reason": "The mock backend examines no evidence, so it cannot verify anything.",
        "evidence_summary": "Not examined.",
        "source_objects": [],
        "claim_evidence_links": [],
        "numeric_check": None,
        "suggested_fix": "None.",
    }


def reviewer_reply(prompt: str, is_retry: bool) -> int:
    reviewer = first(r'- reviewer = "([^"]+)"', prompt)
    paper_id = first(r'- paper_id = "([^"]+)"', prompt)
    prefix = first(r"formatted ([A-Z]+)-001", prompt)
    if not (reviewer and paper_id and prefix):
        print("mock: could not read reviewer, paper_id and id prefix from the prompt", file=sys.stderr)
        return 2

    count = max(0, env_int("ROBUSTO_MOCK_FINDINGS", 2))
    path = evidence_file(paper_id)
    findings = []
    for index in range(1, count + 1):
        if index == count and count > 1:
            findings.append(cannot_verify_finding(prefix, index, reviewer))
        else:
            findings.append(verifiable_finding(prefix, index, reviewer, path))

    payload = {
        "reviewer": reviewer,
        "paper_id": paper_id,
        "run_status": "ok",
        "summary": f"{MOCK_NOTE} {len(findings)} synthetic finding(s) from {reviewer}.",
        "findings": findings,
        "notes": [MOCK_NOTE],
    }

    broken = reviewer in env_names("ROBUSTO_MOCK_FAIL") or (
        reviewer in env_names("ROBUSTO_MOCK_DRIFT") and not is_retry
    )
    if broken:
        payload.pop("run_status")
    emit(payload, fenced=fenced_by_name(reviewer), broken=broken)
    return 0


# --------------------------------------------------------------------------- #
# selector
# --------------------------------------------------------------------------- #

def selector_reply(prompt: str) -> int:
    paper_id = first(r'Classify paper_id "([^"]+)"', prompt)
    catalog = next((block for block in json_blocks(prompt) if isinstance(block, list)), None)
    if not paper_id or catalog is None:
        print("mock: could not read paper_id and the optional-reviewer catalog", file=sys.stderr)
        return 2
    skip = env_names("ROBUSTO_MOCK_SKIP")
    selected = []
    skipped = []
    for entry in catalog:
        name = entry.get("name") if isinstance(entry, dict) else None
        if not name:
            continue
        if name in skip:
            skipped.append({"name": name, "reason": "Skipped on request of ROBUSTO_MOCK_SKIP."})
        else:
            selected.append({"name": name, "reason": "The mock backend selects every conditional specialist."})
    payload = {
        "paper_id": paper_id,
        "paper_type": "empirical_causal",
        "selection_confidence": "high",
        "selection_mode": "applicability",
        "selected_optional_reviewers": selected,
        "skipped_optional_reviewers": skipped,
        "notes": [MOCK_NOTE],
    }
    emit(payload, fenced=False, broken=False)
    return 0


# --------------------------------------------------------------------------- #
# editor
# --------------------------------------------------------------------------- #

def editor_reply(prompt: str) -> int:
    paper_id = first(r'Produce the final markdown report for paper_id "([^"]+)"', prompt)
    if not paper_id:
        print("mock: could not read paper_id from the editor prompt", file=sys.stderr)
        return 2
    bundle_path = Path("work") / paper_id / "editor" / "normalized_bundle.json"
    try:
        bundle = json.loads(bundle_path.read_text(encoding="utf-8"))
    except (OSError, ValueError) as exc:
        print(f"mock: could not read {bundle_path}: {exc}", file=sys.stderr)
        return 2

    canonical = [item for item in bundle.get("canonical_findings", []) if isinstance(item, dict)]
    has_copyedit = any(item.get("issue_class") == "copyedit_issue" for item in canonical)

    # Identifiers may appear only in the traceability appendix, so the body
    # below never prints one.
    lines = [
        "# Multi-Agent Paper Review Report",
        "",
        "**MOCK BACKEND. This is not a review of the manuscript.** Every finding "
        "below is synthetic, generated without reading the paper, so that the "
        "pipeline's assembly, validation and reporting stages could be exercised "
        "without spending model tokens. Discard it once the machinery is proven.",
        "",
        "## Executive Summary",
        "",
        f"This run processed paper `{paper_id}` through the full multi-agent "
        "pipeline with a mock backend standing in for every model call. The "
        "deterministic parse, prompt rendering, schema contract, JSON recovery, "
        "validation, normalisation and editor assembly all ran for real; only the "
        "content of each finding is fabricated. The report therefore says nothing "
        "about the manuscript and everything about whether the pipeline works.",
        "",
        f"The normalised bundle holds {len(canonical)} canonical finding(s). Three "
        "synthetic corrections are listed below purely to populate the required "
        "sections in the shape the real editor uses.",
        "",
        "## Highest-Priority Cross-Agent Findings",
        "",
    ]
    for number in range(1, 4):
        lines += [
            f"### {number}. Synthetic headline finding {number}",
            "",
            "**Evidence.** None was examined. The mock backend fabricates findings "
            "of the correct shape so that each downstream stage receives input.",
            "",
            "**Why it matters.** It does not. The value of this run is that every "
            "stage after the model call executed and validated.",
            "",
            "**Minimum adequate correction.** None. Delete this report once the "
            "real backend has produced a genuine one.",
            "",
        ]
    lines += [
        "## Suggested Revision Priorities",
        "",
        "1. Log the Claude Code CLI in and rerun with the real backend.",
        "2. Read the genuine report that run produces.",
        "3. Treat nothing in this document as a statement about the manuscript.",
        "",
        "## Additional Findings",
        "",
        "### Material Qualifications",
        "",
        "| Area | Location | Issue | Suggested revision |",
        "|---|---|---|---|",
        "| Mock | Mock section | Synthetic qualification generated by the mock backend | None |",
        "",
        "### Exploratory Interpretation and Development",
        "",
        "| Area | Location | Issue | Suggested revision |",
        "|---|---|---|---|",
        "| Mock | Mock section | Synthetic exploratory item generated by the mock backend | None |",
        "",
        "## Items Marked Cannot Verify",
        "",
        "| Item | What is established | What remains unavailable | Proportionate next step |",
        "|---|---|---|---|",
        "| Synthetic cannot-verify items | Nothing; no evidence was examined | Everything | Run the real backend |",
        "",
    ]
    if has_copyedit:
        lines += [
            "## Appendix: Grammar and Copyediting Issues",
            "",
            "| Location | Current text | Issue | Suggested correction |",
            "|---|---|---|---|",
            "| Mock section | synthetic quotation from the mock backend | Synthetic copyedit item | None |",
            "",
        ]
    lines += [
        "## Appendix: Parser and Preprocessing Limitations",
        "",
        "The preflight auditor's synthetic medium-severity parser finding exists to "
        "exercise the warning path. It describes no real limitation of the parsed "
        "artifacts.",
        "",
        "## Appendix: Review Scope and Limitations",
        "",
        "No substantive domain was reviewed. A mock backend answered every model "
        "call with fabricated, schema-valid output. This appendix exists because "
        "the final-report check requires it, and it is accurate: the scope of this "
        "review is empty.",
        "",
        "## Appendix: Traceability Map",
        "",
        "| Report section | Finding | Canonical ID | Source finding IDs |",
        "|---|---|---|---|",
    ]
    for item in canonical:
        canonical_id = item.get("canonical_id") or ""
        sources = ", ".join(
            f"{source.get('reviewer')}:{source.get('id')}"
            for source in item.get("source_findings", [])
            if source.get("reviewer") and source.get("id")
        )
        summary = " ".join(str(item.get("finding_summary") or item.get("summary") or "Synthetic finding").split())
        summary = summary.replace("|", "/")[:80]
        lines.append(f"| Additional Findings | {summary} | {canonical_id} | {sources} |")
    lines.append("")

    sys.stdout.write("\n".join(lines))
    return 0


# --------------------------------------------------------------------------- #

def main() -> int:
    prompt = sys.stdin.read()
    if PROBE_TOKEN in prompt:
        sys.stdout.write(PROBE_TOKEN + "\n")
        return 0
    if EDITOR_MARKER in prompt:
        return editor_reply(prompt)
    if SELECTOR_MARKER in prompt:
        return selector_reply(prompt)
    if CONTRACT_MARKER in prompt:
        return reviewer_reply(prompt, is_retry=RETRY_MARKER in prompt)
    print("mock: unrecognised prompt; no marker found", file=sys.stderr)
    return 2


if __name__ == "__main__":
    raise SystemExit(main())
